config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users, only: [:edit, :update, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :content, presence: true, unless: :image?
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  protect_from_forgery
  
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end  
  
  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json 
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end
  
  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end
  
  def set_group
    @group = Group.find(params[:group_id])
  end
  
end

app/views/messages/_messages.html.haml
.message
  .message__upper-info
    .message__upper-info__talker 
      = messages.user.name
    .message__upper-info__date
      = messages.created_at.strftime("%Y/%m/%d %H:%M")
  .message__text 
    - if messages.content.present?
      %p.lower-message__content
        = messages.content
    = image_tag messages.image.url, class: 'lower-message__image' if messages.image.present?

app/views/messages/index.html.haml
.wrapper
  = render 'shared/side_bar'
  .chat-main
    .main-header
      .main-header__left-box
        %h2.main-header__left-box__current-group{"data-group_id" => ""}
          = @group.name
        %ul.main-header__left-box__member-list
          Member：
          %li.main-header__left-box__member-list__member 
            - @group.group_users.each do |group_user|
              = group_user.user.name
        = link_to edit_group_path(@group) do
          .main-header__edit-btn
            edit
            
    .messages
      = render partial: 'messages', collection: @messages
    
    .form
      = form_for [@group, @message], id: 'new_message' do |f|
        = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        .form__mask
        = f.label :image, class: 'form__mask__image' do
          = fa_icon 'picture-o', class: 'icon'
          = f.file_field :image, class: 'hidden'
        = f.submit value:'Send', class: 'form__submit', "data-disable-with": false